export const projects = [{
        title: 'Google Clone Application',
        description: "This application has the ability to search for up-to-date results, news, images and videos. It also features a modern UI and dark mode. The Front End is built with React components while the styling is done with TailwindCSS. The data used to populate the components are fetched by using the Google Search API from RapidAPI.",
        image: '/images/4.PNG',
        tags: ['React', 'TailwindCSS', 'RapidAPI'],
        source: 'https://goggle-search-engine.netlify.app',
        visit: 'https://github.com/PeroyNel/goggle',
        id: 0,

    },
    {
        title: 'Crypto Dashboard Application',
        description: "This application has the ability to display information regarding the Price, Market Cap and Daily Percentage Change for the most popular crypto currencies. The Front End is built with React along with Ant Design to generate the UI. Charts are displayed by using Charts.JS. The data used to populate this app is generated by using the Coin Ranking API from RapidAPI.",
        image: '/images/3.PNG',
        tags: ['React', 'Ant Design', 'Redux', 'Axios', 'ChartJS'],
        source: 'https://crypto-dash-app.netlify.app/',
        visit: 'https://github.com/PeroyNel/crypto-dashboard-app',
        id: 1,

    },
    {
        title: 'Alan AI News Application',
        description: "This application generates the latest news articles based on a search query that was made by voice command. The Front End has been created with React and Material-UI. The speech recognition capability is handled by Alan AI. The data used to populate this app is generated by the Bing News Search API from RapidAPI.",
        image: '/images/2.PNG',
        tags: ['React', 'MaterialUI', 'Alan AI', 'RapidAPI' ],
        source: 'https://alan-ai-voice-powered-news-app.netlify.app/',
        visit: 'https://github.com/PeroyNel/alan_ai_news_application',
        id: 2,
    },
    {
        title: 'MERN Memories Application',
        description: "This application allows users to log in via Email or Google and then to create, edit, like or remove posts from their catalogue. The Front End was done with React and Material-UI. The Back End was built with Node.JS, Express, Axios and MongoDB. The app relies on using  Redux and Reducers to handle state management, aided by Thunk to manage the middleware.",
        image: '/images/1.png',
        tags: ['React', 'Node', 'Express', 'Axios', 'MongoDB', 'Redux'],
        source: 'https://mern-memories-full-application.netlify.app/posts',
        visit: 'https://github.com/PeroyNel/mern_memories-application',
        id: 3,
    },
];

export const TimeLineData = [
    { year: 2021, month: 'February', text: 'My first "hello world" project', },
    { year: 2021, month: 'April', text: 'First experience with website projects', },
    { year: 2021, month: 'August', text: 'First Javascript project experience', },
    { year: 2021, month: 'September', text: 'First React project experience', },
    { year: 2021, month: 'October', text: 'First Full Stack project experience', },
];